### ISSUE TITLE
How to test the vars plugin?

### ISSUE THREAD

**Issue by abeluck** [ansible-collections/community.sops#13]
The old pre-collections PR for the sops vars plugins was easy to test , just drop it in a `plugins/var` dir, add `vars_plugins` to your ansible.cfg and you were off.

However now things are more complicated, and aren't working.

I have the collection installed from my reqs file:

```yaml
collections:
  - type: git
    name: https://github.com/ansible-collections/community.sops.git
    version: 762eec08170d98d1a253cb2aa6fe120fa1f98b80
```

Yet, Ansible isn't picking up the plugin.
