### ISSUE TITLE
community.sops.load_vars not updating global variable

### ISSUE THREAD

**Issue by silentpete** [ansible-collections/community.sops#201]
##### SUMMARY
I attempting to update default loaded variables with the sops load_vars action and the variable isn't updating. If I set a new variable in the sops encrypted file (not already existing in global variables) it works as expected.

Also, if I use `ansible.builtin.include_vars` with a non sops encrypted file, it will update the global variable as expected.

Looking at the load precedence I believe it should update the variable. Ref: <https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable>

Sorry if this is a known issue and thank you for what you do and any help,
Peter

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.sops.load_vars

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible [core 2.15.12]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/vagrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/vagrant/.ansible/collections:/usr/share/ansible/collections:/etc/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.18 (main, Jul  3 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] (/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION

```paste below
$ ansible-galaxy collection list community.sops
# /etc/ansible/collections/ansible_collections
Collection     Version
-------------- -------
community.sops 1.8.2
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
COLLECTIONS_PATHS(/etc/ansible/ansible.cfg) = ['/home/vagrant/.ansible/collections', '/usr/share/ansible/collections', '/etc/ansible/collections']
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_GATHER_TIMEOUT(/etc/ansible/ansible.cfg) = 30
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = This file is managed by ansible, do not make changes here - they will be overwritten: Source file: {file}
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
DEFAULT_VAULT_PASSWORD_FILE(/etc/ansible/ansible.cfg) = /home/vagrant/ansibleVault.key
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Localhost, Rocky Linux 9.4

##### STEPS TO REPRODUCE

```
#!/usr/local/bin/ansible-playbook
---
- name: Some Playbook
  hosts: localhost
  become: true
  become_method: ansible.builtin.sudo
  vars_files:
    - vars.yml

  tasks:
    - name: output
      ansible.builtin.debug:
        var: some_variable

    - name: "Load secret variables from SOPS encrypted file"
      community.sops.load_vars:
        file: vars.sops.yml

    - name: output
      ansible.builtin.debug:
        var: some_variable
```

##### EXPECTED RESULTS

```
$ ansible-playbook /code/playground/ansible_sops_update_vars_testing/playbook.yml -i /etc/ansible/hosts -v
Using /etc/ansible/ansible.cfg as config file

PLAY [Some Playbook] ****************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************
ok: [localhost]

TASK [output] ***********************************************************************************************************************************************************
ok: [localhost] =>
  some_variable: from vars.yml

TASK [Load secret variables from SOPS encrypted file] *******************************************************************************************************************
ok: [localhost] => changed=false
  ansible_facts:
    some_variable: from vars.sops.yml
  ansible_included_var_files:
  - /code/playground/ansible_sops_update_vars_testing/vars/vars.sops.yml

TASK [output] ***********************************************************************************************************************************************************
ok: [localhost] =>
  some_variable: from vars.sops.yml

PLAY RECAP **************************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

##### ACTUAL RESULTS

```paste below
$ ansible-playbook /code/playground/ansible_sops_update_vars_testing/playbook.yml -i /etc/ansible/hosts -v
Using /etc/ansible/ansible.cfg as config file

PLAY [Some Playbook] ****************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************
ok: [localhost]

TASK [output] ***********************************************************************************************************************************************************
ok: [localhost] =>
  some_variable: from vars.yml

TASK [Load secret variables from SOPS encrypted file] *******************************************************************************************************************
ok: [localhost] => changed=false
  ansible_facts:
    some_variable: from vars.sops.yml
  ansible_included_var_files:
  - /code/playground/ansible_sops_update_vars_testing/vars/vars.sops.yml

TASK [output] ***********************************************************************************************************************************************************
ok: [localhost] =>
  some_variable: from vars.yml

PLAY RECAP **************************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by felixfontein** [comment]
It's unclear to me where "actions/modules that return `ansible_facts`" should be in https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable - because that's the precedence "variables" loaded by `community.sops.load_vars` end up with.

It's indeed strange that while `ansible.builtin.include_vars` and `ansible.builtin.set_fact` (both with `cacheable: true` and `cacheable: false`) can override `vars_files` content, modules/actions returning `ansible_facts` apparently cannot.

Right now you can only work around it like this:
```
---
- name: Some Playbook
  hosts: localhost
  become: true
  become_method: ansible.builtin.sudo
  vars_files:
    - vars.yml

  tasks:
    - name: output
      ansible.builtin.debug:
        var: some_variable

    - name: "Load secret variables from SOPS encrypted file"
      community.sops.load_vars:
        file: vars.sops.yml
      register: loaded_sops_vars

    - name: Work-around
      set_fact:
        some_variable: "{{ loaded_sops_vars.ansible_facts.some_variable }}"

    - name: output
      ansible.builtin.debug:
        var: some_variable
```

I don't know whether this is a bug in ansible-core, or whether this is intentional...
