### ISSUE TITLE
Decrypt secrets that are loaded through other lookup_plugins

### ISSUE THREAD

**Issue by hhenkel** [ansible-collections/community.sops#67]
##### SUMMARY
From my brief understanding of how the sops plugins are intended to be used I got the impression, that values are decrypted when the are "loaded" through one of the plugins. I'm wondering if it is possible to decrypt the data later down the line, so that one could use a different lookup plugin to load the encrypted data and then ansible would decrypt it once it is used.

##### ISSUE TYPE
- Feature Idea

**Comment by felixfontein** [comment]
You mean like a lookup `community.sops.decrypt_sops` so you can do things like `lookup('file', '/path/to/data.yaml.sops') | community.sops.decrypt_sops` (with potentially some steps inbetween)?

Sure, that should be possible to implement. Decrypting sops files does not require `.sops.yaml` so piping something through sops without ever hitting the disk should work fine.

**Comment by hhenkel** [comment]
@felixfontein yes, I guess that would help solving the issue. Would it be possible to pipe a complex structure (like an array) with some encrypted data through, so that one would receive the whole structure, unencrypted data?

May there arise an issue when passing that to a role in regards to [the lazy evaluation the lookup](https://github.com/ansible/ansible/issues/9623) ? 
```
- name: Install SignalFX Agent
  include_role:
    name: signalfx-agent
    apply:
      vars:
        signalfx: "{{ lookup('jerakia', 'namespace=signalfx-agent') | community.sops.decrypt_sops }}"
  tags:
    - signalfx-agent
```
(unrelated) Or is there a better way to not run into the issue of lazy evaluation when querying remote resources and preventing the possibility to receive different values throughout a playbook run as data might change in the background?
