### ISSUE TITLE
Support setting sops_binary option for vars plugin

### ISSUE THREAD

**Issue by Lycowolf** [ansible-collections/community.sops#80]
##### SUMMARY

Please expose sops_binary in ansible.cfg

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
community.sops.sops vars plugin

##### ADDITIONAL INFORMATION

It's currently not possible to set sops_binary for vars plugin, as it's not possible to use variables to configure vars plugin, and the setting is not exposed in ansible.cfg. This would be useful when creating a self-contained Ansible packages: SOPS is statically-linked binary that works everywhere and can be simply included in a package, but vars plugin looks for it in PATH only.

Please expose sops_binary option in the ansible.cfg, e. g. using

```yaml
sops_binary:
    description:
        - Path to the sops binary.
        - By default uses C(sops).
    type: path
    version_added: 1.0.0
    ini:
        - key: sops_binary
          section: community.sops
```

If I am mistaken and there is a way to set it, please document it.
